USE [master]
GO

/****** Object:  Database [ServiceDiscovery]    Script Date: 12/5/2023 6:12:55 PM ******/
CREATE DATABASE [ServiceDiscovery]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ServiceDiscovery', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ServiceDiscovery.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ServiceDiscovery_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ServiceDiscovery_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServiceDiscovery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ServiceDiscovery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET ARITHABORT OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ServiceDiscovery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ServiceDiscovery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ServiceDiscovery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ServiceDiscovery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET RECOVERY FULL 
GO

ALTER DATABASE [ServiceDiscovery] SET  MULTI_USER 
GO

ALTER DATABASE [ServiceDiscovery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ServiceDiscovery] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ServiceDiscovery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ServiceDiscovery] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ServiceDiscovery] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ServiceDiscovery] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ServiceDiscovery] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ServiceDiscovery] SET  READ_WRITE 
GO


